### ISSUE TITLE
Need a better UI ❗ 

### ISSUE THREAD

**Issue by Jake1924** [Jake1924/Meet-Bot#4]
### :black_heart: DESIGN BETTER UI :black_heart:

 :skull_and_crossbones: **The chrome extension popup can be designed more attractive, it's as same as it was made for testing.** :skull_and_crossbones:

![image](https://user-images.githubusercontent.com/77602579/155850082-6758b65e-4023-48fd-a773-3be11c498a82.png) ![image](https://user-images.githubusercontent.com/77602579/155850108-9ab34764-660c-4761-9bbe-bc3a81e466f4.png)

:black_heart: :black_heart: [**REFER**](https://github.com/Jake1924/Meet-Bot/blob/master/ChromeExtension/popup.html) :black_heart: :black_heart:

**Comment by judy-n** [comment]
Hi! I'd like to work on this, can you assign me this issue?

**Comment by Jake1924** [comment]
Thank you @judy-n for contributing !! 

Closing this issue for this version .
